# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 2.2"

gem "sinatra-contrib", "~> 2.2"

gem "erubis", "~> 2.7"

gem "redcarpet", "~> 3.5"

group :development do
  gem "rubocop", "= 0.86.0"
  gem "rubocop-minitest", "~> 0.9.0"
  gem "rubocop-rake", "~> 0.5.1"
end

group :test do
  gem "minitest", "~> 5.15"
  gem "rack-test", "~> 1.1"
end

gem "bcrypt", "~> 3.1"
